server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arduino
    username: arduino
    password: arduino
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - db.migration